# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

before:
  hooks:
    - go mod download
builds:
  - id: coredns
    main: ./cmd/coredns.go
    binary: coredns
    ldflags:
      - -X main.pluginVersion={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
