# Go development environment
FROM golang:1.24.1-alpine

# Install necessary tools
RUN apk add --update --no-cache bash curl jq openssh
RUN apk add --update --no-cache git --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main

# Create a non-root user
RUN adduser -D -h /home/vscode -s /bin/bash vscode \
    && echo "vscode ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    
# Set the user to vscode
USER vscode

# Install Go binary packages
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Set the working directory
WORKDIR /workspace

# Expose port for debugging
EXPOSE 8080